Language-File: 'en.yml'
Debug: false
Updater: true
Top:
  Amount: 10 #How many players should we show in '/coins top'
  Cooldown: 300 #Cooldown in seconds
Format:
  Symbol: '$'
  Single: 'Coin'
  Plural: 'Coins'
Database:
  Server: 'Lobby'
  ForceUpdate: true #Update local players once their balances update
  PoolSize: 2
  MySQL:
    host: 'localhost'
    port: 3306
    database: 'root'
    username: 'root'
    tablePrefix: 'BE_'
    password: 'password'